# See https://symfony.com/doc/current/email/dev_environment.html
#swiftmailer:
#    send all emails to a specific address
#    delivery_addresses: ['me@example.com']

swiftmailer:
    delivery_addresses: ['aleksander.buczek.pro@gmail.com']